# Define your start paths here (this file is optional if crawl_domain_for_new_paths = true)
paths:
    - /
    - /klaviere-stuttgart
    - /service/eventservice
    - /service/finanzieren
    - /service/klavier-mieten-stuttgart
    - /service/klavierstimmer-stuttgart
    - /service/reparatur
    - /unternehmen/referenzen
